### ISSUE TITLE
Possibilty of adding `podman` support

### ISSUE THREAD

**Issue by anoopcs9** [ishworkh/docker-image-artifact#3]
I just wanted to check on how difficult it is to have support for `podman` along with `docker` which is common and often preferred by various projects out there.

**Comment by phlogistonjohn** [comment]
I'll add that 99.9% of the time the podman command lines are compatible with docker (intentionally). So in cases where the docker CLI is invoked it's usually just a matter of replacing 'docker' with 'podman' based on a configuration option.

**Comment by anoopcs9** [comment]
@ishworkh we would love to see the podman support added. Is that planned to be worked on anytime soon?

**Comment by ishworkh** [comment]
Hi @anoopcs9 , yes it is planned. Just have been prioritising other stuffs over it until now. Now other stuffs are done, i will focus on this.

You can expect something to be done about it in next couple of weeks.

**Comment by ishworkh** [comment]
Hei, checkout https://github.com/ishworkh/container-image-artifact.
I decided to create generic package that would cover different container engines (docker and podman atm) instead of adding a support for podman here. Initially it was planned for docker hence it was named `docker-image-*` - which does not go well if more engines are supported.

And following, new github actions are created with generic package. Plz check them out. Would appreciate any kind of feedbacks 😉 .

- https://github.com/marketplace/actions/container-image-artifact-upload 
- https://github.com/marketplace/actions/container-image-artifact-download actions.

**Comment by anoopcs9** [comment]
> Hei, checkout https://github.com/ishworkh/container-image-artifact. I decided to create generic package that would cover different container engines (docker and podman atm) instead of adding a support for podman here. Initially it was planned for docker hence it was named `docker-image-*` - which does not go well if more engines are supported.
> 
> And following, new github actions are created with generic package. Plz check them out. Would appreciate any kind of feedbacks wink .
> 
>     * https://github.com/marketplace/actions/container-image-artifact-upload
> 
>     * https://github.com/marketplace/actions/container-image-artifact-download actions.

Many thanks. I could successfully make use of new GitHub action with both `docker` and `podman` engines. I really appreciate the hard work put in to come up with an entire new action.
